prompt: "You are a grader assessing relevance of a retrieved document to a user question. \n 
    Here is the retrieved document: \n\n {document} \n\n
    Here is the user question: {question} \n
    If the document contains keywords related to the user question, grade it as relevant. \n
    It does not need to be a stringent test. The goal is to filter out erroneous retrievals. \n
    Give a binary score 'yes' or 'no' score to indicate whether the document is relevant to the question. \n
    Provide the binary score as a JSON with a single key 'score' and no premable or explanation.
    "
rewrite_prompt: "You a question re-writer that converts an input question to a better version that is optimized \n 
            for vectorstore retrieval. Look at the initial and formulate an improved question. \n
            Here is the initial question: \n\n {question}. Improved question with no preamble: \n"

input_variables: ["question", "document"]
rewrite_prompt_input_variables: ["generation", "question"]
run_local: True
local_llm: gdisney/mistral-uncensored